import React, { useState } from 'react';
import { Code, Download, FileCode, Copy, Check } from 'lucide-react';
import { downloadProjectZip } from '../api';

export default function CodeStudio({ codeData }) {
  if (!codeData || !codeData.files) return null;

  const fileNames = Object.keys(codeData.files);
  const [activeFile, setActiveFile] = useState(fileNames[0] || '');
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(codeData.files[activeFile] || '');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadZip = () => {
    downloadProjectZip(codeData.files, codeData.project_name || "nexus_generated_app");
  };

  return (
    <div className="glass-panel glass-panel-glow" style={{ padding: '1.25rem', marginTop: '1rem' }}>
      {/* Header Bar */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{ padding: '8px', borderRadius: '8px', background: 'rgba(16, 185, 129, 0.2)', border: '1px solid rgba(16, 185, 129, 0.4)' }}>
            <Code size={20} color="#34d399" />
          </div>
          <div>
            <h4 style={{ fontSize: '0.95rem', fontWeight: 800, color: '#f3f4f6' }}>
              Multi-File Code Project: {codeData.project_name || 'generated_app'}
            </h4>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              {fileNames.length} Files Generated by Coder Agent
            </span>
          </div>
        </div>

        <button 
          onClick={handleDownloadZip} 
          className="btn-primary"
          style={{ background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)', boxShadow: '0 4px 14px rgba(16, 185, 129, 0.3)' }}
        >
          <Download size={16} /> Export Project ZIP
        </button>
      </div>

      {/* Code Workbench Panel */}
      <div style={{ borderRadius: '8px', overflow: 'hidden', border: '1px solid var(--border-color)', background: '#030712' }}>
        {/* File Tabs Bar */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: '#0f172a', borderBottom: '1px solid var(--border-color)', overflowX: 'auto' }}>
          <div style={{ display: 'flex' }}>
            {fileNames.map((fn) => {
              const isActive = fn === activeFile;
              return (
                <button
                  key={fn}
                  onClick={() => setActiveFile(fn)}
                  style={{
                    padding: '8px 14px',
                    border: 'none',
                    background: isActive ? '#030712' : 'transparent',
                    color: isActive ? '#34d399' : 'var(--text-muted)',
                    fontSize: '0.8rem',
                    fontWeight: isActive ? 600 : 400,
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '6px',
                    borderBottom: isActive ? '2px solid #34d399' : '2px solid transparent',
                    whiteSpace: 'nowrap'
                  }}
                >
                  <FileCode size={14} /> {fn}
                </button>
              );
            })}
          </div>

          <button 
            onClick={handleCopy}
            style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '8px 14px', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.75rem' }}
          >
            {copied ? <Check size={14} color="#34d399" /> : <Copy size={14} />}
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>

        {/* Code Content View */}
        <pre style={{ padding: '1.25rem', overflowX: 'auto', fontFamily: 'var(--font-mono)', fontSize: '0.82rem', color: '#e2e8f0', lineHeight: '1.5', maxHeight: '350px' }}>
          <code>{codeData.files[activeFile] || '// Select a file to view code'}</code>
        </pre>
      </div>
    </div>
  );
}
