import os
import io
import zipfile
from typing import Dict, Any, List

class CoderAgent:
    def __init__(self):
        self.name = "Coder & Project Builder Agent"

    def generate_project(self, prompt: str) -> Dict[str, Any]:
        """
        Generates a complete multi-file project based on the user's prompt.
        Returns file tree structure and raw code for each file.
        """
        project_name = "generated_app"
        lowered = prompt.lower()

        if "react" in lowered or "weather" in lowered or "frontend" in lowered or "dashboard" in lowered:
            files = {
                "package.json": '''{
  "name": "nexus-generated-app",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "lucide-react": "^0.263.1"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@vitejs/plugin-react": "^4.0.3",
    "vite": "^4.4.5"
  }
}''',
                "index.html": '''<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated Nexus App</title>
    <style>
      body { margin: 0; font-family: system-ui, sans-serif; background: #0f172a; color: #f8fafc; }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>''',
                "src/main.jsx": '''import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)''',
                "src/App.jsx": f'''import React, { useState } from 'react';

export default function App() {{
  const [query, setQuery] = useState('');
  const [data, setData] = useState(null);

  const handleSearch = () => {{
    setData({{
      title: "Result for: " + (query || "Default Task"),
      status: "Active",
      timestamp: new Date().toLocaleTimeString()
    }});
  }};

  return (
    <div style={{{{ padding: '2rem', maxWidth: '600px', margin: '0 auto' }}}}>
      <h1>🚀 Nexus Studio App</h1>
      <p>Generated by Multiagent Coder for prompt: <em>"{prompt}"</em></p>
      
      <div style={{{{ display: 'flex', gap: '10px', marginTop: '1.5rem' }}}}>
        <input 
          type="text" 
          value={{query}} 
          onChange={{(e) => setQuery(e.target.value)}}
          placeholder="Enter prompt..."
          style={{{{ flex: 1, padding: '10px', borderRadius: '6px', border: '1px solid #334155', background: '#1e293b', color: '#fff' }}}}
        />
        <button 
          onClick={{handleSearch}}
          style={{{{ padding: '10px 20px', borderRadius: '6px', background: '#3b82f6', color: '#fff', border: 'none', cursor: 'pointer', fontWeight: 'bold' }}}}
        >
          Execute
        </button>
      </div>

      {{data && (
        <div style={{{{ marginTop: '2rem', padding: '1.5rem', background: '#1e293b', borderRadius: '8px', border: '1px solid #334155' }}}}>
          <h3>{{data.title}}</h3>
          <p>Status: <span style={{{{ color: '#10b981' }}}}>{{data.status}}</span></p>
          <small>Generated at: {{data.timestamp}}</small>
        </div>
      )}}
    </div>
  );
}}''',
                "README.md": f'''# Generated Project: {project_name}

Created by NexusLM Multiagent System.

## Run Instructions
```bash
npm install
npm run dev
```
'''
            }
        else:
            # Python CLI/FastAPI Project default
            files = {
                "main.py": f'''# Main execution generated for: {prompt}
import sys
import time

def main():
    print("=" * 50)
    print("🚀 NexusLM Multiagent Code Executable")
    print(f"Task Prompt: {prompt}")
    print("=" * 50)
    
    print("[1/3] Initializing task context...")
    time.sleep(0.5)
    print("[2/3] Executing core pipeline...")
    time.sleep(0.5)
    print("[3/3] Task successfully completed!")

if __name__ == "__main__":
    main()
''',
                "requirements.txt": "requests>=2.31.0\npydantic>=2.0.0\n",
                "README.md": f'''# Python Tool for: {prompt}
Created by NexusLM Coder Agent.

## Usage
```bash
python main.py
```
'''
            }

        return {
            "project_name": project_name,
            "files": files,
            "file_list": list(files.keys())
        }

    @staticmethod
    def create_zip_bytes(files: Dict[str, str]) -> bytes:
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
            for file_path, content in files.items():
                zf.writestr(file_path, content)
        buffer.seek(0)
        return buffer.getvalue()
